### ISSUE TITLE
Add layers for administrative regions such as County borders

### ISSUE THREAD

**Issue by mskyttner** [bioatlas/geoserver-docker#2]
Specifically this layer:

http://slwgeo.artdata.slu.se:8080/geoserver/SLW/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=SLW:artdatabankenslanskarta&maxFeatures=50&outputFormat=SHAPE-ZIP

But also for example other relevant regions, such as municipality regions and lanscaps. Also relevant biogeographical regions if available, such as old provinces used for botanical data.

Perhaps these could be of relevance:

https://data.val.se/val/val2018/statistik/2018_valgeografi_lan.zip
https://data.val.se/val/val2018/statistik/2018_valgeografi_landsting.zip
https://data.val.se/val/val2018/statistik/2018_valgeografi_kommuner.zip

(counties and municipalities)

from

https://data.val.se/val/val2018/statistik/index.html

What about landscapes?

**Comment by ronquist** [comment]
Is this assigned to someone? Does it need to be discussed by ExO?

**Comment by mskyttner** [comment]
@shahmanash is working on it, AFAIK, and I don't think it needs discussing by the Exo, what do you think @shahmanash?

**Comment by shahmanash** [comment]
I cannot say whether or not ExO needs to discuss these content related issues. It might be an overlap as we are doing it in the TC and within our group. Christian had assembled a list of layers https://github.com/bioatlas/data-mobilization-pipeline/blob/master/spatial-batch/layers.csv . Once the components are up to date, I will try to pull in the layers in batches. If there are some layers missing we can add/update , if not necessary we can delete/not upload those.
