### ISSUE TITLE
Missing instructions for connecting with pgAdmin

### ISSUE THREAD

**Issue by mskyttner** [bioatlas/geoserver-docker#4]
The postgis component does not have ports opened outside of the SDN / network used in the docker composition.

Therefore an external connection to it is currently closed.

The Makefile describes how to load data and restore an existing database (from a backup): https://github.com/bioatlas/geoserver-docker/blob/master/Makefile#L52-L53

If external connectivity is needed, ports needs to be opened up by adding a stanza to the docker-compose.yml file and firewall needs to be opened up in the IaaS, probably also pg_hba.conf needs to allow external connections.

However, by doing an ssh-tunnel to the box, pgAdmin could connect to the postgis if only the ports are opened up in the docker-compose.yml file - which seems a better approach.

**Comment by mskyttner** [comment]
With this change f984cbd40941e131e64a8df02801a5e13f2dd66f the ports are opened up to the host where the docker containers are running.

Starting the project locally with

`make up`

makes it possible to use pgAdmin with the following setup (note that now due to it being available on the host, you can use the name 'localhost' to connect to it):

![image](https://user-images.githubusercontent.com/1715840/46144224-9527e680-c25c-11e8-8c3c-31c45b18d961.png)

In order to do the same thing on the production server, an ssh tunnel is needed (search for ways to do this, for example https://www.skyverge.com/blog/how-to-set-up-an-ssh-tunnel-with-putty/), then the procedure would be the same after that.

**Comment by vasnick** [comment]
Working tunnel settings in Putty:
![image](https://user-images.githubusercontent.com/42643358/46145218-c0f89b80-c25f-11e8-8595-78c3c51034f3.png)

**Comment by mskyttner** [comment]
To have the change in f984cbd stick on the server, a git pull and restart of the service is needed. I did that. So it should be possible to use pgAdmin to access the postgis layersdb over an ssh tunnel. 

The command used to restart is `docker-compose restart postgis` once the port has been opened usings the `ports:` directive in the `docker-compose.yml`-file. Then you should see it open as reported by the `docker-compose ps` command:

`geoserver-docker_postgis_1     docker-entrypoint.sh postgres    Up      0.0.0.0:5432->5432/tcp   `
