### ISSUE TITLE
No access to geoserver_data dir

### ISSUE THREAD

**Issue by vasnick** [bioatlas/geoserver-docker#5]
I cannot access /opt/geoserver/data_dir.

**Comment by mskyttner** [comment]
The DATA_DIR should be there at the location described here: https://github.com/bioatlas/geoserver-docker/blob/master/Dockerfile#L5

Data there ends up persisted in a docker volume as shown here:
https://github.com/bioatlas/geoserver-docker/blob/master/docker-compose.yml#L59

The question is what you need to do with it? Copy files into it?

**Comment by vasnick** [comment]
Yes, copy static shape files.

**Comment by mskyttner** [comment]
A file can be copied into the container like this:

`docker cp shapefile geoserver-docker_geoserver_1:/opt/geoserver/data_dir/`

It might be better to volume mount files into the container or even add them into the Dockerfile at build time, if pre-seeding the image with data.

Or in this instance to use the geoserver UI to add the shapefile?
